name: sksurv-test
channels:
  - conda-forge
  - defaults
dependencies:
  - coverage
  - cython>=3.0
  - ecos
  - joblib
  - matplotlib>=3.8.0,<3.9
  - numexpr
  - numpy=*
  - osqp!=0.6.0,!=0.6.1
  - packaging
  - pandas=*
  - pip
  - pytest
  - python=*
  - scikit-learn==*
  - scipy>=1.6.0
  - seaborn>=0.11.2,<0.12
  - setuptools-scm
  - wheel
  - pip:
    - black[jupyter]>=23.3.0,<23.4
    - build
    - nbval>=0.10.0
    - tomli

